/*
 * Copyright (c) 2026 ShakaCode LLC.
 *
 * SPDX-License-Identifier: LicenseRef-ShakaPerf-1.0
 *
 * This file is part of ShakaPerf. Use is governed by The ShakaPerf
 * License in LICENSE.md.
 */

import sharp from 'sharp';

export async function bufferToWebpDataUri(buf: Buffer, quality: number): Promise<string> {
  const webp = await sharp(buf).webp({ quality }).toBuffer();
  return `data:image/webp;base64,${webp.toString('base64')}`;
}

export async function bufferToJpegDataUri(buf: Buffer, quality: number): Promise<string> {
  const jpeg = await sharp(buf).jpeg({ quality }).toBuffer();
  return `data:image/jpeg;base64,${jpeg.toString('base64')}`;
}

// AVIF is encoded through libheif, which rejects any image whose width or
// height exceeds 16384px ("Processed image is too large for the HEIF format").
// Full-page screenshots of tall pages blow past this, so the longest side is
// clamped into the box before encoding.
const HEIF_MAX_DIMENSION = 16384;

export async function bufferToAvifDataUri(
  buf: Buffer,
  quality: number,
  scale = 1,
): Promise<string> {
  const meta = await sharp(buf).metadata();
  const srcWidth = meta.width ?? 0;
  const srcHeight = meta.height ?? 0;
  const oversized = srcWidth > HEIF_MAX_DIMENSION || srcHeight > HEIF_MAX_DIMENSION;
  let pipeline = sharp(buf);
  if (oversized) {
    // Box the image into the HEIF limit, preserving aspect ratio, so a tall
    // page encodes instead of throwing. A requested downscale is still honored:
    // never wider than round(srcWidth * scale).
    const requestedWidth =
      scale > 0 && scale < 1 && srcWidth
        ? Math.max(1, Math.round(srcWidth * scale))
        : HEIF_MAX_DIMENSION;
    pipeline = sharp(buf).resize({
      width: Math.min(requestedWidth, HEIF_MAX_DIMENSION),
      height: HEIF_MAX_DIMENSION,
      fit: 'inside',
      withoutEnlargement: true,
    });
  } else if (scale > 0 && scale < 1) {
    const width = srcWidth ? Math.max(1, Math.round(srcWidth * scale)) : undefined;
    pipeline = sharp(buf).resize({ width, withoutEnlargement: true });
  }
  const avif = await pipeline.avif({ quality, effort: 2 }).toBuffer();
  return `data:image/avif;base64,${avif.toString('base64')}`;
}

export async function bufferToWebpDataUriScaled(
  buf: Buffer,
  quality: number,
  scale = 1,
): Promise<string> {
  let pipeline = sharp(buf);
  if (scale > 0 && scale < 1) {
    const meta = await pipeline.metadata();
    const width = meta.width ? Math.max(1, Math.round(meta.width * scale)) : undefined;
    pipeline = sharp(buf).resize({ width, withoutEnlargement: true });
  }
  const webp = await pipeline.webp({ quality }).toBuffer();
  return `data:image/webp;base64,${webp.toString('base64')}`;
}

const IMG_DATA_URI_RE = /data:image\/(?:png|jpeg|jpg|webp);base64,([A-Za-z0-9+/]+=*)/g;
const IMG_DATA_URI_FULL_RE = /data:image\/(?:png|jpeg|jpg|webp);base64,[A-Za-z0-9+/]+=*/g;

// Wraps a single timeline frame (control/experiment screenshot or diff frame).
// Generated by `bench/core/timeline-comparison.ts` `renderScreenshots` /
// `renderDiffFrames` — both use `<div class="screenshot-entry">`.
const TIMELINE_FRAME_RE = /<div class="screenshot-entry[^"]*"[^>]*>[\s\S]*?<\/div>/g;

// Drop every Nth frame from a generated `timeline_comparison.html` to halve
// (or further reduce) the embedded frame rate without re-running engines.
// Frames are absolutely positioned by `top:Xpx`, so removing every other one
// keeps the surviving frames at the right visual times.
export function decimateTimelineFrames(html: Buffer, keepEvery: number): Buffer {
  if (keepEvery <= 1) return html;
  const text = html.toString('utf8');
  let i = -1;
  const out = text.replace(TIMELINE_FRAME_RE, (m) => {
    i += 1;
    return i % keepEvery === 0 ? m : '';
  });
  return Buffer.from(out, 'utf8');
}

export interface CompressHtmlImagesOpts {
  imageQuality: number;
  stripPatterns?: RegExp[];
  outputFormat?: 'webp' | 'jpeg';
}

export async function compressHtmlImages(
  html: Buffer,
  opts: CompressHtmlImagesOpts,
): Promise<Buffer> {
  let text = html.toString('utf8');

  if (opts.stripPatterns) {
    for (const pattern of opts.stripPatterns) {
      text = text.replace(pattern, '');
    }
  }

  const matches = [...text.matchAll(IMG_DATA_URI_RE)];
  if (matches.length === 0) return Buffer.from(text, 'utf8');

  const replacements = await Promise.all(
    matches.map(async (m) => {
      const base64 = m[1];
      const buf = Buffer.from(base64, 'base64');
      try {
        if (opts.outputFormat === 'jpeg') {
          return await bufferToJpegDataUri(buf, opts.imageQuality);
        }
        return await bufferToWebpDataUri(buf, opts.imageQuality);
      } catch (err) {
        // Lighthouse renders a trailing `…` in network-table cells for long
        // data URIs; the regex then captures only a base64 prefix that sharp
        // can't decode. Valid base64 has length % 4 === 0, so a non-multiple
        // is a reliable truncation signal. Anything else is a real decode
        // failure (corrupt image, libvips error, OOM) and the report would
        // silently embed the unmodified URI — warn so it's not invisible.
        const looksTruncated = base64.length % 4 !== 0;
        if (!looksTruncated) {
          console.warn(
            `[shaka-perf compress] sharp failed to decode a data URI ` +
              `(${m[0].length} chars, prefix ${m[0].slice(0, 32)}…): ${(err as Error).message}`,
          );
        }
        return m[0];
      }
    }),
  );

  // Replace from the end so earlier offsets don't shift.
  let out = text;
  for (let i = matches.length - 1; i >= 0; i--) {
    const m = matches[i];
    const webp = replacements[i];
    out = out.slice(0, m.index!) + webp + out.slice(m.index! + m[0].length);
  }

  return Buffer.from(out, 'utf8');
}

export interface CompressSvgEmbeddedImagesOpts {
  imageQuality: number;
  maxWidthPx: number;
}

export async function compressSvgEmbeddedImages(
  svgText: string,
  opts: CompressSvgEmbeddedImagesOpts,
): Promise<string> {
  const matches = [...svgText.matchAll(IMG_DATA_URI_FULL_RE)];
  if (matches.length === 0) return svgText;

  const replacements = await Promise.all(
    matches.map(async (m) => {
      const original = m[0];
      const base64 = original.slice(original.indexOf('base64,') + 'base64,'.length);
      const input = Buffer.from(base64, 'base64');
      const resized = await sharp(input)
        .resize({ width: opts.maxWidthPx, withoutEnlargement: true })
        .webp({ quality: opts.imageQuality })
        .toBuffer();
      return `data:image/webp;base64,${resized.toString('base64')}`;
    }),
  );

  let out = svgText;
  for (let i = matches.length - 1; i >= 0; i--) {
    const match = matches[i];
    out = out.slice(0, match.index!) + replacements[i] + out.slice(match.index! + match[0].length);
  }
  return out;
}
