yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  '@loadable/babel-plugin@*':
    dependencies:
      '@babel/helper-plugin-utils': '*'
  ts-jest@*:
    dependencies:
      jest-util: '*'
