export type {
  Status,
  Category,
  VisregArtifact,
  PerfMetric,
  PerfMetricGroup,
  PerfDirection,
  PerfArtifact,
  AxeArtifact,
  AxeScanArtifact,
  AxeViolationArtifact,
  AxeViolationNodeArtifact,
  CategoryResult,
  TestResult,
  ReportMeta,
  ReportData,
} from '../../src/compare/report';
