import sharp from 'sharp';

export async function bufferToWebpDataUri(buf: Buffer, quality: number): Promise<string> {
  const webp = await sharp(buf).webp({ quality }).toBuffer();
  return `data:image/webp;base64,${webp.toString('base64')}`;
}

const IMG_DATA_URI_RE = /data:image\/(?:png|jpeg|jpg);base64,([A-Za-z0-9+/]+=*)/g;

// Wraps a single timeline frame (control/experiment screenshot or diff frame).
// Generated by `bench/core/timeline-comparison.ts` `renderScreenshots` /
// `renderDiffFrames` — both use `<div class="screenshot-entry">`.
const TIMELINE_FRAME_RE = /<div class="screenshot-entry[^"]*"[^>]*>[\s\S]*?<\/div>/g;

// Drop every Nth frame from a generated `timeline_comparison.html` to halve
// (or further reduce) the embedded frame rate without re-running engines.
// Frames are absolutely positioned by `top:Xpx`, so removing every other one
// keeps the surviving frames at the right visual times.
export function decimateTimelineFrames(html: Buffer, keepEvery: number): Buffer {
  if (keepEvery <= 1) return html;
  const text = html.toString('utf8');
  let i = -1;
  const out = text.replace(TIMELINE_FRAME_RE, (m) => {
    i += 1;
    return i % keepEvery === 0 ? m : '';
  });
  return Buffer.from(out, 'utf8');
}

export interface CompressHtmlImagesOpts {
  imageQuality: number;
  // Each pattern is matched against the raw HTML and removed before image rewriting.
  // Use multi-line patterns with the `g` flag to drop entire DOM regions
  // (e.g. Lighthouse's filmstrip block).
  stripPatterns?: RegExp[];
}

export async function compressHtmlImages(
  html: Buffer,
  opts: CompressHtmlImagesOpts,
): Promise<Buffer> {
  let text = html.toString('utf8');

  if (opts.stripPatterns) {
    for (const pattern of opts.stripPatterns) {
      text = text.replace(pattern, '');
    }
  }

  const matches = [...text.matchAll(IMG_DATA_URI_RE)];
  if (matches.length === 0) return Buffer.from(text, 'utf8');

  const replacements = await Promise.all(
    matches.map(async (m) => {
      const original = m[0];
      const base64 = m[1];
      try {
        const buf = Buffer.from(base64, 'base64');
        const webp = await bufferToWebpDataUri(buf, opts.imageQuality);
        return { original, webp };
      } catch {
        return { original, webp: original };
      }
    }),
  );

  // Replace from the end so earlier offsets don't shift.
  let out = text;
  for (let i = matches.length - 1; i >= 0; i--) {
    const m = matches[i];
    const { webp } = replacements[i];
    if (webp === m[0]) continue;
    out = out.slice(0, m.index!) + webp + out.slice(m.index! + m[0].length);
  }

  return Buffer.from(out, 'utf8');
}
